{
 "title": "Chainlink Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LINK price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"}"
    }
   ]
  },
  {
   "title": "ETH price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}"
    }
   ]
  },
  {
   "title": "LINK / ETH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"} / on() exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}"
    }
   ]
  },
  {
   "title": "ETH usage /h",
   "type": "gauge",
   "description": "ETH usage for Fluxmonitor Chainlink server",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "delta(eth_balance{instance=\"chainlink01:80\"}[1h]) * -1"
    }
   ]
  },
  {
   "title": "Earnings USD",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"})  * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total USD node ETH"
    },
    {
     "expr": "sum(chainlink_rewards_ocr_total) * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total USD node OCR"
    },
    {
     "expr": "sum(chainlink_rewards_matic_total)  * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total USD node Matic"
    },
    {
     "expr": "(sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"} + on () chainlink_rewards_ocr_total{job_type=\"ocr\"} + on () chainlink_rewards_matic_total{job_type=\"matic\"}) * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total General USD"
    }
   ]
  },
  {
   "title": "Earnings ETH",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"})  * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"} / on() exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total ETH node ETH"
    },
    {
     "expr": "sum(chainlink_rewards_ocr_total) * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"} / on() exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total ETH node OCR"
    },
    {
     "expr": "sum(chainlink_rewards_matic_total)  * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"} / on() exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total ETH node Matic"
    },
    {
     "expr": "(sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"} + on () chainlink_rewards_ocr_total{job_type=\"ocr\"} + on () chainlink_rewards_matic_total{job_type=\"matic\"}) * on() exchange_rates{chain_id=\"chainlink\", instance=\"monitoring01:9100\"} / on() exchange_rates{chain_id=\"ethereum\", instance=\"monitoring01:9100\"}",
     "legendFormat": "Total General ETH"
    }
   ]
  },
  {
   "title": "Gas price",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "geth_gas_price{service=\"geth_exporter\", instance=\"geth_instance01:9090\"} / 1000000000",
     "legendFormat": "GWEI"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "geth_gas_price{service=\"geth_exporter\", instance=\"geth_instance01:9090\"} / 1000000000"
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eth_balance{account=\"0x000000000000000000000000000000000000\"}"
    }
   ]
  },
  {
   "title": "ETH Balance OCR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "eth_balance{account=\"0x000000000000000000000000000000000000\"}"
    }
   ]
  },
  {
   "title": "Total Link ETH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"}"
    }
   ]
  },
  {
   "title": "Total Link OCR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "chainlink_rewards_ocr_total" }
   ]
  },
  {
   "title": "Total Link Matic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "chainlink_rewards_matic_total" }
   ]
  },
  {
   "title": "Total Link General",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(chainlink_rewards_fluxmonitor_total{job_type=\"fluxmonitor\"}) + on () chainlink_rewards_runlog{job_type=\"runlog\"} + on () chainlink_rewards_ocr_total{job_type=\"ocr\"} + on () chainlink_rewards_matic_total{job_type=\"matic\"}"
    }
   ]
  },
  { "title": "ETH Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ETH Jobs",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "chainlink_rewards_fluxmonitor", "legendFormat": "{{job_name}} " },
    { "expr": "chainlink_rewards_runlog", "legendFormat": "Runlog " }
   ]
  },
  {
   "title": "Burn rate for ETH Node",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "delta(eth_balance{account=\"0x000000000000000000000000000000000000\",job=\"chainlink_exporter\"}[1h])<0",
     "legendFormat": "Rate account {{account}}"
    }
   ]
  },
  { "title": "OCR Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "OCR Jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "chainlink_rewards_ocr", "legendFormat": "{{job_name}} " }
   ]
  },
  {
   "title": "Burn rate for OCR Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "delta(eth_balance{account=\"0x000000000000000000000000000000000000\",job=\"chainlink_exporter\"}[1h])<0",
     "legendFormat": "Rate account {{account}}"
    }
   ]
  },
  { "title": "Matic Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Matic Jobs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "chainlink_rewards_matic", "legendFormat": " {{job_name}} " }
   ]
  }
 ]
}